# Generated by Django 5.2.1 on 2025-05-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsubmission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
